BEGIN;
INSERT INTO pizzas (name, price) values ('Margarita', 19.90);
INSERT INTO pizzas (name, price) values ('Cappriciosa', 22.90);
INSERT INTO pizzas (name, price) values ('Vesuvio', 25.90);

INSERT INTO components (name, price) values ('Cheese', 4.50);
INSERT INTO components (name, price) values ('Ham', 4.50);
INSERT INTO components (name, price) values ('Salami', 4.50);
INSERT INTO components (name, price) values ('Mushrooms', 4.50);

INSERT INTO drinks (name, price, capacity) values ('Coca-Cola', 3.00, 0.33);
INSERT INTO drinks (name, price, capacity) values ('Coca-Cola', 4.00, 0.5);
INSERT INTO drinks (name, price, capacity) values ('Coca-Cola', 6.00, 1);
INSERT INTO drinks (name, price, capacity) values ('Fanta', 3.00, 0.33);
INSERT INTO drinks (name, price, capacity) values ('Fanta', 4.00, 0.5);
INSERT INTO drinks (name, price, capacity) values ('Fanta', 6.00, 1);
INSERT INTO drinks (name, price, capacity) values ('Sprite', 3.00, 0.33);
INSERT INTO drinks (name, price, capacity) values ('Sprite', 4.00, 0.5);
INSERT INTO drinks (name, price, capacity) values ('Sprite', 6.00, 1);
COMMIT;
BEGIN;
INSERT INTO pizzas (name, price) values ('Hawajska',23.90);
INSERT INTO pizzas (name, price) values ('Tonno',24.90);
INSERT INTO pizzas (name, price) values ('Pepperoni',21.90);
INSERT INTO pizzas (name, price) values ('Monza',22.90);
INSERT INTO pizzas (name, price) values ('Farmerska',27.90);

INSERT INTO components (name, price) values ('Chicken', 5.50);
INSERT INTO components (name, price) values ('Onion', 3.50);
INSERT INTO components (name, price) values ('Garlic', 3.50);
COMMIT;
INSERT INTO users (last_name, first_name, role, email, phone, created_at) values ('Pietraszko', 'Jerzy', 'manager', 'jerzypietraszko@o2.pl', 666148804, NOW());
INSERT INTO addresses (city, zip_code, address, user_id) values ('Wroclaw', '51-156', 'ul. Wybrzeze Wyspianskiego 2' ,(SELECT user_id FROM users WHERE phone = 666148804));
INSERT INTO pizza_components (pizza_id, comp_id) values(1, 1);
INSERT INTO pizza_components (pizza_id, comp_id) values(2, 1);
INSERT INTO pizza_components (pizza_id, comp_id) values(2, 2);
INSERT INTO pizza_components (pizza_id, comp_id) values(3, 1);
INSERT INTO pizza_components (pizza_id, comp_id) values(3, 3);
INSERT INTO pizza_components (pizza_id, comp_id) values(3, 4);
INSERT INTO pizza_components (pizza_id, comp_id) values(4, 1);
INSERT INTO pizza_components (pizza_id, comp_id) values(4, 4);
INSERT INTO pizza_components (pizza_id, comp_id) values(4, 5);
INSERT INTO pizza_components (pizza_id, comp_id) values(4, 6);
INSERT INTO pizza_components (pizza_id, comp_id) values(5, 1);
INSERT INTO pizza_components (pizza_id, comp_id) values(5, 2);
INSERT INTO pizza_components (pizza_id, comp_id) values(5, 6);
INSERT INTO pizza_components (pizza_id, comp_id) values(6, 1);
INSERT INTO pizza_components (pizza_id, comp_id) values(6, 3);
INSERT INTO pizza_components (pizza_id, comp_id) values(6, 4);
INSERT INTO pizza_components (pizza_id, comp_id) values(7, 1);
INSERT INTO pizza_components (pizza_id, comp_id) values(7, 5);
INSERT INTO pizza_components (pizza_id, comp_id) values(7, 6);
INSERT INTO pizza_components (pizza_id, comp_id) values(8, 1);
INSERT INTO pizza_components (pizza_id, comp_id) values(8, 2);
INSERT INTO pizza_components (pizza_id, comp_id) values(8, 3);
